### ISSUE TITLE
GNOME Firmware is not showing up at App Center

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnome.Firmware#2]
![Captura de tela de 2019-09-13 16-46-58](https://user-images.githubusercontent.com/26097419/64890471-20ed7b00-d646-11e9-97f9-d26515786855.png)

**Comment by hughsie** [comment]
I think this should be fixed by https://gitlab.gnome.org/hughsie/gnome-firmware-updater/commit/d1a46544e7d8966598d44cbd65b0c069656101e9
