### ISSUE TITLE
Flatpak broken, does not recognize any firmware

### ISSUE THREAD

**Issue by corecontingency** [flathub/org.gnome.Firmware#4]
Found this while testing my pull request #3 , however this also happens on the stable version from flathub.

EDIT: Since my #3 was merged so fast (thanks, btw), just wanted to clarify that this error was happening on the stable version of the flatpak from flathub before my pull request was merged, so this issue is not caused by my pull request.

Here are the error messages when I first open org.gnome.Firmware:

[Failed to load list of remotes](https://imgur.com/a/IaMWqcZ)
[Failed to load device list](https://imgur.com/a/3liBWrx)

And after I close those two error messages, and enable the LVFS, this error message pops up:

[Failed to enable LVFS](https://imgur.com/a/XRNR6uB)

And then after closing this error message, no firmware is detected, and there is an infinite spinning circle.

Running Arch, with GNOME on Xorg. Also have a btrfs filesystem with subvolumes.

I tried installing [gnome-firmware](https://www.archlinux.org/packages/community/x86_64/gnome-firmware/) from the Arch community repository afterwards, and it works, and detects my hardware with no errors.

Does the flatpak not support btrfs?

**Comment by hughsie** [comment]
Seems to work here on Fedora 32 for me. Do other GNOME apps packaged as flatpaks work on your system? Could you also have perhaps disabled the org.freedesktop.fwupd sandbox permission?

**Comment by corecontingency** [comment]
> Do other GNOME apps packaged as flatpaks work on your system?

Yup. Other flatpak apps work fine.

> Could you also have perhaps disabled the org.freedesktop.fwupd sandbox permission?

Haven't touched any sandbox settings, and
`flatpak override --show org.gnome.Firmware`
shows no overrides set.

I think this might be a btrfs issue. There are some other flatpak apps that get confused also, see [thunderbird](https://github.com/flathub/org.mozilla.Thunderbird/issues/4#issuecomment-601945243), and [sysprof](https://gitlab.gnome.org/GNOME/sysprof/issues/34).

**Comment by hughsie** [comment]
> I think this might be a btrfs issue.

**Comment by hughsie** [comment]
> I think this might be a btrfs issue.

I don't think many people have btrfs root filesystems, me included I'm afraid.

**Comment by corecontingency** [comment]
Yeah, I will test if it is still broken in a openSUSE Tumbleweed VM (they also use a root btrfs filesystem).

If that is the case, I will open up a issue in the flatpak github repository, because I have found several other programs that are broken, and this seems to be a flatpak issue (Just found that the flatpak for gnome-contacts is likewise broken).

Thanks!
